services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - media_net
    volumes:
      - ${PWD}/radarr:/config:rw
      - ${PWD}/../data/downloads:/downloads:rw
      - ${PWD}/../data/movies:/movies:rw
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    security_opt:
      - no-new-privileges:true
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - media_net
    volumes:
      - ${PWD}/sonarr:/config:rw
      - ${PWD}/../data/downloads:/downloads:rw
      - ${PWD}/../data/tv_shows:/tv:rw
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    security_opt:
      - no-new-privileges:true
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
      
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      - media_net
    volumes:
      - ${PWD}/qbittorrent:/config:rw
      - ${PWD}/../data/downloads:/downloads:rw
      - ${PWD}/../data/downloads/incomplete:/downloads/incomplete:rw
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8081
    security_opt:
      - no-new-privileges:true
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    networks:
      - media_net
    volumes:
      - ${PWD}/jackett:/config:rw
      - ${PWD}/../data/downloads:/downloads:rw
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    security_opt:
      - no-new-privileges:true
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped

networks:
  media_net:
    name: media_net
    driver: bridge
